export const FETCH_HOUR_LIST_SUCCESS = "FETCH_HOUR_LIST_SUCCESS";
export const DETAIL_CHANGED = "DETAIL_CHANGED";
export const DATA_SAVED_SUCCESS = "DATA_SAVED_SUCCESS";
export const DATA_ERROR = "DATA_ERROR";
export const CLEAR_FORM_DATA = "CLEAR_FORM_DATA";
export const SORT_CHANGED = "SORT_CHANGED";
export const FILTERD_LIST_SUCCESS = "FILTERD_LIST_SUCCESS";
